output_dir: .data/new

global_parameters:
  targets: targets.yaml
  seed: 0
  cuda_id: 1

workflows:
  - name: visual
    nodes:
      - name: SimpleImageGenerator
        parameters:
          num_images: 3
          model_id: SdxlTurbo
          steps: 3
          cfg: 0
      - name: ImageFeatureExtractor
        parameters:
          model_id: VisionTransformer
      - name: VectorCombiner
        parameters:
          method: mean
          dim: 0
