output_dir: ./data/new

global_parameters:
  targets:
    cupcake: [cup, cake]
  seed: 0
  cuda_id: 0

workflows:
  - name: visual
    nodes:
      - name: SimpleImageGenerator
        parameters:
          num_images: 3
          model_id: SdxlTurbo
          steps: 1
          cfg: 1
      - name: ImageFeatureExtractor
        parameters:
          model_id: VisionTransformer
