output_dir: .data/output/reddy_0

global_parameters:
  targets: .data/input/reddy/reddy_targets.yaml
  seed: 0
  cuda_id: 1

workflows:
  - name: textual
    nodes:
      - name: TextFeatureExtractor
        parameters:
          model_id: FastText
      - name: SimilarityMeasurer
        parameters:
          measure: cosine
          dim: 0
      - name: ResultCombiner
        parameters:
          file_name: similarities.csv
      - name: CorrelationCalculator
        parameters:
          input_file_0: .data/output/reddy_0/textual/2_result_combiner/similarities.csv
          input_file_1: .data/input/reddy/reddy.csv
          columns_0: [1,2]
          columns_1: [1, 3]
          output_header: [corr_const_1, corr_const_2]
